
ecampus.roles.faculty=913
ecampus.roles.student=914
ecampus.roles.admin=901
ecampus.roles.dean-ap=902
ecampus.roles.registrar=905

ecampus.academic.current-academic-year-id=
ecampus.academic.current-academic-year-name=2025-26
ecampus.academic.current-term-id=35
ecampus.academic.current-term-name=Winter
